/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadgrupo5.vistas;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
//import static org.mariadb.jdbc.internal.util.pool.Pools.close;

/**
 *
 * @author Asus
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(500,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icono=new ImageIcon(getClass().getResource("/universidadgrupo5/recursos/Universidad.jpg"));
        Image miImagen=icono.getImage();
        escritorio = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){

                g.drawImage(miImagen,0,0,getWidth(),getHeight(),this);
            }

        };
        jMenuBar2 = new javax.swing.JMenuBar();
        jMAlumnos = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMMateria = new javax.swing.JMenu();
        JMMaterias = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMinscripciones = new javax.swing.JMenuItem();
        jMNotas = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        consultaPorMateria = new javax.swing.JMenuItem();
        jSalirProgram = new javax.swing.JMenu();
        jSalirSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        jMAlumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universidadgrupo5/recursos/alumno.png"))); // NOI18N

        jMenuItem2.setText("Formulario de Alumno");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMAlumnos.add(jMenuItem2);

        jMenuBar2.add(jMAlumnos);

        jMMateria.setText("Materia");

        JMMaterias.setText("Formulario de Materias");
        JMMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMMateriasActionPerformed(evt);
            }
        });
        jMMateria.add(JMMaterias);

        jMenuBar2.add(jMMateria);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universidadgrupo5/recursos/administracion.png"))); // NOI18N
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        jMinscripciones.setText("Manejo de Inscripciones");
        jMinscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMinscripcionesActionPerformed(evt);
            }
        });
        jMenu5.add(jMinscripciones);

        jMNotas.setText("Manipulacion de Notas");
        jMNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMNotasActionPerformed(evt);
            }
        });
        jMenu5.add(jMNotas);

        jMenuBar2.add(jMenu5);

        jMenu6.setText("Consultas");

        consultaPorMateria.setText("Consulta por Materia");
        consultaPorMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaPorMateriaActionPerformed(evt);
            }
        });
        jMenu6.add(consultaPorMateria);

        jMenuBar2.add(jMenu6);

        jSalirProgram.setText("Salir");
        jSalirProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirProgramActionPerformed(evt);
            }
        });

        jSalirSistema.setText("Salir del Sistema");
        jSalirSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirSistemaActionPerformed(evt);
            }
        });
        jSalirProgram.add(jSalirSistema);

        jMenuBar2.add(jSalirProgram);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Formulario alumno
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        FormularioAlumnoView alumno = new FormularioAlumnoView();
        alumno.setVisible(true);
        //cambia color de fondo
        alumno.getContentPane().setBackground(new Color(68, 167, 132));
        escritorio.add(alumno);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    
    //formulario de materias
    private void JMMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMMateriasActionPerformed
        // TODO add your handling code here:
         escritorio.removeAll();
        escritorio.repaint();
        GestionMaterias materia = new GestionMaterias();
        materia.setVisible(true);
        materia.getContentPane().setBackground(new Color(68, 167, 132));
        escritorio.add(materia);
    
                                    
    }//GEN-LAST:event_JMMateriasActionPerformed

    private void jMinscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMinscripcionesActionPerformed
        {                                           
       ///////////////////// REVISAR ESTO
        escritorio.removeAll();
        escritorio.repaint();
        FormularioInscripcion inscriptas = new FormularioInscripcion();
        inscriptas.setVisible(true);
        inscriptas.getContentPane().setBackground(new Color(68, 167, 132));
        escritorio.add(inscriptas);
    }                            
    }//GEN-LAST:event_jMinscripcionesActionPerformed

    private void jSalirProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirProgramActionPerformed
       dispose(); // finalizar programa (FY)
    }//GEN-LAST:event_jSalirProgramActionPerformed

    private void jMNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMNotasActionPerformed
        // TODO add your handling code here:
        
         escritorio.removeAll();
        escritorio.repaint();
        FormularioNota nota = new FormularioNota();
        nota.setVisible(true);
        nota.getContentPane().setBackground(new Color(68, 167, 132));
        escritorio.add(nota);
    }//GEN-LAST:event_jMNotasActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void consultaPorMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaPorMateriaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioConsulta con = new FormularioConsulta();
        con.setVisible(true);
        con.getContentPane().setBackground(new Color(68, 167, 132));
        escritorio.add(con);
    }//GEN-LAST:event_consultaPorMateriaActionPerformed

    private void jSalirSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirSistemaActionPerformed
        dispose();
    }//GEN-LAST:event_jSalirSistemaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMMaterias;
    private javax.swing.JMenuItem consultaPorMateria;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMAlumnos;
    private javax.swing.JMenu jMMateria;
    private javax.swing.JMenuItem jMNotas;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMinscripciones;
    private javax.swing.JMenu jSalirProgram;
    private javax.swing.JMenuItem jSalirSistema;
    // End of variables declaration//GEN-END:variables
}
